name: country
main: com.github.w0819.plugin.Main
api-version: "1.17"
version: 0.0.2
libraries:
  - io.github.monun:kommand:2.6.6
  - io.github.monun:tap:4.1.9
  - net.projecttl:InventoryGUI-api:4.1.5
